[nrf fromtree] [nrfconnect] Fix for jsonschema documentation and factory data script
nrfconnect/sdk-connectedhomeip pull request #161
Opened 2022-12-06 10:15 UTC by ArekBalysNordic

In the factory data script, there was no checking if a user has jsonschema module installed. That caused an error even if the user did not want to use that way of JSON validation.

Added checking a jsonschema module in python script for generating factory data and added proper information in the documentation about how to obtain jsonschema python module.

2022-12-06 10:24 UTC, Damian-Nordic approved these changes

2022-12-06 10:24 UTC, Damian-Nordic commented on docs/guides/nrfconnect_factory_data_configuration.md
> +an additional argument. Do do it complete the following steps:
```suggestion
file generation. For this to happen, you must install jsonschema Python module 
in your Python environment and provide the path to the JSON schema file as
an additional argument. To do it, complete the following steps:
```

2022-12-06 10:24 UTC, Damian-Nordic commented on docs/guides/nrfconnect_factory_data_configuration.md
> +1. Install jsonschema python module
```suggestion
1. Install jsonschema Python module
```

2022-12-06 14:48 UTC, greg-fer requested changes

2022-12-06 14:48 UTC, greg-fer commented on docs/guides/nrfconnect_factory_data_configuration.md
> +file generation. For this to happen, you must install jsonschema Python module
```suggestion
file generation. For this to happen, you must install the `jsonschema` Python module 
```

2022-12-06 14:48 UTC, greg-fer commented on docs/guides/nrfconnect_factory_data_configuration.md
> +an additional argument. To do it, complete the following steps:
```suggestion
an additional argument. To do this, complete the following steps:
```

2022-12-06 15:02 UTC, markaj-nordic approved these changes

2022-12-08 06:42 UTC, greg-fer approved these changes

2022-12-09 11:34 UTC, merged