Added network core reset for the NRF53 when calling PlatformMgr::Shut…
nrfconnect/sdk-connectedhomeip pull request #390
Opened 2024-02-19 11:40 UTC by bdlr2

Linked to my case on the DevZone https://devzone.nordicsemi.com/f/nordic-q-a/108101/device-crash-when-doing-a-software-reset

When calling the function `PlatformMgr().Shutdown();` (intentionally, or through a factory reset) a Hard Fault happens because the communication is broken/not in sync anymore between the App and Net cores of the NRF5340. My fix proposes to first reset the network core then reset the application core.

2024-03-20 13:58 UTC, LuDuda requested changes
Hello @bdlr2,

Thank you for your contribution.

I believe we should not need to call `nrf_reset_network_force_off` in the Matter platform, as this should be handled internally by `sys_reboot`.

Have you encountered this issue on the nRF5340DK, or only on a custom board? If I had to guess, it's possible you've designed your own board and the `nrf5340_cpunet_reset.c` file has not been included in board's `CMakeLists.txt`. You can find an example here (note the if-statement): [nRF5340DK CMakeLists.txt](https://github.com/nrfconnect/sdk-zephyr/blob/v3.5.99-ncs1/boards/arm/nrf5340dk_nrf5340/CMakeLists.txt#L4-L7).

2024-03-21 07:40 UTC, bdlr2 commented
Hello @LuDuda, thanks for the feedback.
That's indeed on a custom board, but I double checked and the `nrf5340_cpunet_reset.c` is included properly in the `CMakelists.txt`. My board was derived from the nRF5340DK to avoid this kind of issues.

2024-10-09 19:28 UTC, LuDuda commented
> Hello @LuDuda, thanks for the feedback. That's indeed on a custom board, but I double checked and the `nrf5340_cpunet_reset.c` is included properly in the `CMakelists.txt`. My board was derived from the nRF5340DK to avoid this kind of issues.

@bdlr2 Have you been able to check the newest SDK if the problem still exists? As i mentioned above, I would like to fix this issue outside of the Matter code.

2024-10-10 06:42 UTC, bdlr2 commented
@LuDuda no, I didn't check yet.

2025-01-20 01:59 UTC, closed without merging